 version: "3.7"

 services:
    app:
      build: .
      command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
      ports:
        - 3000:3000
      working_dir: /app
      volumes:
        - ./:/app
      environment:
            DB_USER: root
            DB_NAME: insta-api
            DB_PASSWORD: 123456789
            DB_HOST: mysql

    mysql:
      image: mysql:5.7
      volumes:
        - insta-mysql-data:/var/lib/mysql
      environment:
            MYSQL_ROOT_PASSWORD: 123456789
            MYSQL_DATABASE: insta-api

    elasticsearch:
      image: elasticsearch:7.17.6
      hostname: "elasticsearch"
      environment:
          - discovery.type=single-node
      ports:
            - "9200:9200"

      
 volumes:
      insta-mysql-data: