version: '2'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: insta-api
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "3307:3306"
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/insta_api"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: insta-api
      DB_PASSWORD: 123456789
      DB_HOST: db
