version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: insta-api
      MYSQL_USER: muhammad
      MYSQL_PASSWORD: 123456789
    ports:
      - "3307:3306"
  app:
    build: .
    command: 
          bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/noteapp"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: muhammad
      DB_NAME: insta-api
      DB_PASSWORD: 123456789
      DB_HOST: db
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2-arm64
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
        - xpack.monitoring.enabled=false
        - xpack.graph.enabled=false
        - xpack.watcher.enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./docker_data/elasticsearch/data:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
  