mysql:
  image: mysql:5.6.34
  ports:
    - "3307:3306"
  environment:
    - MYSQL_ROOT_PASSWORD: 123456789
    - MYSQL_DATABASE: insta-api
app:
  build: .
  environment:
    RAILS_ENV: development
  ports:
    - '3000:3000'
  volumes_from:
    - appdata
  links:
    - "mysql"
