default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: insta-api
  username: root
  password: 123456789
  host: 127.0.0.1
  port: 3306
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default