default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  # un comment those to use rails s
  #database: insta-api
  #username: root
  #password: 123456789
  #host: 127.0.0.1  
  ########################
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  #############################
development:
  <<: *default

test:
  <<: *default