default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: insta-api
  username: root
  password: 123456789
  host: <%= ENV['DB_HOST'] %s>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default