default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 123456789
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>
  database: insta-api
  socket: /var/run/mysqld/mysqlx.sock

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default